version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8000:8000"
        volumes:
            - ./api-allied:/api-allied
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:fpm
        volumes:
            - ./api-allied:/api-allied
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
